// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'a': string;
  'bigPlay': string;
  'controls': string;
  'currentTime': string;
  'duration': string;
  'enterFullscreenBtn': string;
  'error': string;
  'errorIcon': string;
  'errorMessage': string;
  'exitFullscreenBtn': string;
  'fullScreenBtns': string;
  'hidden': string;
  'loading': string;
  'pauseBtn': string;
  'playBtn': string;
  'playPauseBtns': string;
  'player': string;
  'progressBar': string;
  'progressBarBackground': string;
  'progressBarBuffered': string;
  'progressBarCursor': string;
  'progressBarFill': string;
  'quality': string;
  'qualityBtns': string;
  'qualityConditioner': string;
  'qualityRow': string;
  'toolBar': string;
  'toolBarBtn': string;
  'toolBarBtns': string;
  'toolBarIcons': string;
  'topProgressBar': string;
  'topProgressBarFill': string;
  'touchable': string;
  'video': string;
  'volume': string;
  'volumeBackground': string;
  'volumeBtns': string;
  'volumeConditioner': string;
  'volumeCursor': string;
  'volumeFill': string;
  'volumeOffBtn': string;
  'volumeOnBtn': string;
}
declare var cssExports: CssExports;
export = cssExports;
